version: '3.8'

services:
  # 前端应用
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    # 如果需要挂载配置文件
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    
  # 如果有后端服务，可以取消注释以下配置
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   depends_on:
  #     - database
  
  # 如果需要数据库，可以取消注释以下配置
  # database:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: yiji
  #     MYSQL_USER: yiji
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   mysql_data:
#     driver: local